Fix /users patch endpoint, add more fields to model
boolean-uk/team-dev-server-ex-2410-team1 pull request #14
Opened 2024-10-28 13:44 UTC by gremble0

Add more fields to the model and database.
Update swagger documentation.

2024-10-28 14:53 UTC, JosteinRuen approved these changes, later dismissed
Amazing work

2024-10-29 09:08 UTC, JosteinRuen approved these changes, later dismissed
Great job updating the model

2024-10-29 10:00 UTC, thomaafl approved these changes, later dismissed
lovely code

2024-10-29 10:06 UTC, allendewilzin requested changes

2024-10-29 10:06 UTC, allendewilzin commented on docs/openapi.yml
> +                $ref: '#/components/schemas/CreatedUser'
why is the response createdUser model. 

user wont exist anymore

2024-10-29 10:12 UTC, gremble0 commented on docs/openapi.yml
> +                $ref: '#/components/schemas/CreatedUser'
The model for a created user and a deleted user is the same so no need to duplicate. Renamed `CreatedUser` to `User` to better reflect

2024-10-29 10:13 UTC, allendewilzin approved these changes

2024-10-29 10:13 UTC, allendewilzin commented
Good code.

2024-10-29 10:15 UTC, thomaafl approved these changes

2024-10-29 10:15 UTC, merged